theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - TRIAGE.md
  - TEST.md
  - README.md
  - OLDREADME.md
- name: GitHub Issues to Azure DevOps
  uses: danhellem/github-actions-issue-to-work-item@1.5
